Rois debug numbering
danforthcenter/plantcv pull request #1488
Opened 2024-04-10 14:59 UTC by HaleySchuhl

**Describe your changes**
update _draw_roi method to add order number to debug image whenever there are multiple ROIs 

**Type of update**
Is this a:
* New feature or feature enhancement
* Work in progress

**Associated issues**
- closes #1487 
- 
**Additional context**
Add any other context about the problem here.

**For the reviewer**
See [this page](https://plantcv.readthedocs.io/en/latest/pr_review_process/) for instructions on how to review the pull request.
- [ ] PR functionality reviewed in a Jupyter Notebook
- [ ] All tests pass
- [ ] Test coverage remains 100%
- [ ] Documentation tested
- [ ] New documentation pages added to `plantcv/mkdocs.yml`
- [ ] Changes to function input/output signatures added to `updating.md`
- [ ] Code reviewed
- [ ] PR approved

2024-04-12 14:25 UTC, HaleySchuhl commented
![image](https://github.com/danforthcenter/plantcv/assets/44006936/f09d45ae-e0b0-4696-908d-670ca6c0eb4e)
![image](https://github.com/danforthcenter/plantcv/assets/44006936/f5a73b19-2a11-473c-8ed4-c7a28c34365c)

2024-04-12 21:02 UTC, HaleySchuhl commented
Not really sure how these changes impact the results from `pcv.closing` but can dig into this next week.

2024-04-17 15:08 UTC, dhiraj-ms requested changes

2024-04-17 15:08 UTC, dhiraj-ms commented on docs/roi_multi.md
>  lbl_mask, n_lbls = pcv.create_labels(mask=mask, rois=rois)
Change 'createa' to 'create'  in the above sentence.

2024-04-23 21:06 UTC, merged