Adding simple rgb tutorial to the tutorial gallergy
danforthcenter/plantcv pull request #1502
Opened 2024-04-22 14:40 UTC by annacasto

**Describe your changes**
Adding a simple RGB workflow to the tutorial gallery. This tutorial is a straight-forward computer vision workflow and contains references to other workflows with options for more complexity. 

**Type of update**
Is this a:
* New feature or feature enhancement

**Associated issues**
None

**Additional context**

**For the reviewer**
See [this page](https://plantcv.readthedocs.io/en/latest/pr_review_process/) for instructions on how to review the pull request.
- [ ] PR functionality reviewed in a Jupyter Notebook
- [ ] All tests pass
- [ ] Test coverage remains 100%
- [ ] Documentation tested
- [ ] New documentation pages added to `plantcv/mkdocs.yml`
- [ ] Changes to function input/output signatures added to `updating.md`
- [ ] Code reviewed
- [ ] PR approved

2024-04-22 21:39 UTC, annacasto commented
Keely, I updated the index.ipynb notebook with the optional color correction step, so it should be all set for final review now.

2024-04-23 14:43 UTC, k034b363 reviewed
Looks good to me, just one typo to fix before the histogram (says "Creating a histogram of pixel insenity"). I also might suggest, since this is supposed to be super basic, that it would be helpful to include something like "you must do math to get the height and width of the ROI".

2024-04-25 16:08 UTC, annacasto commented
Fixed typos and added some more context

2024-04-26 14:29 UTC, k034b363 approved these changes

2024-04-26 16:56 UTC, annacasto commented
Fixed the title of the tutorial and added Workflow Inputs

2024-05-02 14:38 UTC, HaleySchuhl requested changes
WorkflowInputs error resolve with re-running from the top, and maybe extra buttons (since binder is inconsistently functional)

2024-05-02 14:47 UTC, annacasto commented on docs/tutorials/simple_rgb_tutorial.md
> +[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/danforthcenter/plantcv-tutorial-simple-rgb-workflow.git/HEAD) Check out our interactive tutorial!
Awesome thanks! I wasn't sure what we wanted that to look like. I'll add in those buttons.

2024-05-02 19:36 UTC, annacasto commented on docs/tutorials/simple_rgb_tutorial.md
> +[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/danforthcenter/plantcv-tutorial-simple-rgb-workflow.git/HEAD) Check out our interactive tutorial!
Buttons added!

2024-05-14 15:35 UTC, nfahlgren commented
@annacasto could you rerun the notebook and sync it to the tutorial repo? Currently it is rendered with an error:

<img width="657" alt="Screenshot 2024-05-14 at 10 35 22 AM" src="https://github.com/danforthcenter/plantcv/assets/6233508/bd2c7f5e-d7d5-4500-ab45-d18475d8d545">

2024-05-16 17:08 UTC, merged