Auto color correct wrapper
danforthcenter/plantcv pull request #1625
Opened 2024-11-05 16:37 UTC by HaleySchuhl

**Describe your changes**
Adds a wrapper that enables someone to do color corrections in one step. 

**Type of update**
Is this a:
* New feature or feature enhancement

**Associated issues**
Reference associated issue numbers. Does this pull request close any issues?

**Additional context**
Add any other context about the problem here.

**For the reviewer**
See [this page](https://plantcv.readthedocs.io/en/latest/pr_review_process/) for instructions on how to review the pull request.
- [ ] PR functionality reviewed in a Jupyter Notebook
- [ ] All tests pass
- [ ] Test coverage remains 100%
- [ ] Documentation tested
- [ ] New documentation pages added to `plantcv/mkdocs.yml`
- [ ] Changes to function input/output signatures added to `updating.md`
- [ ] Code reviewed
- [ ] PR approved

2024-11-08 21:45 UTC, nfahlgren requested changes

2024-11-08 21:45 UTC, nfahlgren commented on docs/updating.md
> +* post v4.6: corrected_img = **plantcv.transform.r**(*rgb_img, label=None, **kwargs*)
Typo in function name

2024-11-08 21:45 UTC, nfahlgren commented on tests/plantcv/transform/test_auto_correct_color.py
> +
```suggestion


```

2024-11-13 22:17 UTC, k034b363 commented on docs/transform_auto_correct_color.md
Looks like the example images for before and after color correction are different samples.

2024-12-04 19:24 UTC, HaleySchuhl commented on docs/transform_auto_correct_color.md
Thanks for catching this. I just reused the readable debug image from an existing doc page, and removed the one I had added. Hopefully should be good to go now.

2024-12-13 20:12 UTC, k034b363 approved these changes
Looks good to me! Test notebook with two additional images added to drive.

2024-12-13 23:24 UTC, nfahlgren approved these changes

2024-12-13 23:24 UTC, merged