Add a function that plots histograms for hyperspectral images
danforthcenter/plantcv pull request #742
Opened 2021-04-02 14:43 UTC by DannieSheng

**Describe your changes**
Add a function that plots histograms for hyperspectral images with given wavelengths of interest

**Type of update**
Is this a:
* New feature or feature enhancement
* Work in progress

**Associated issues**
Discussion #685

2021-04-27 18:19 UTC, HaleySchuhl requested changes

2021-04-27 18:19 UTC, HaleySchuhl commented on docs/visualize_hyper_histogram.md
> +**plantcv.visualize.histogram**(*array, mask=None, bins=100, lower_bound=None, upper_bound=None, title=None, wvlengths=[480, 550, 670]*)
**plantcv.visualize. hyper_histogram**(*array, mask=None, bins=100, lower_bound=None, upper_bound=None, title=None, wvlengths=[480, 550, 670]*)

2021-04-27 18:21 UTC, HaleySchuhl approved these changes

2021-07-23 20:16 UTC, nfahlgren approved these changes
Thanks @DannieSheng, looks great!

2021-07-23 20:25 UTC, DannieSheng commented
> Thanks @DannieSheng, looks great!

Thanks for making changes!

2021-07-23 20:56 UTC, merged