Create time lapse video (visualize sub package)
danforthcenter/plantcv pull request #762
Opened 2021-04-26 14:28 UTC by DannieSheng

**Describe your changes**
Add a function to create time-lapse video in the `visualize` sub-package 

**Type of update**
Is this a:
* New feature

2021-04-29 20:55 UTC, JorgeGtz requested changes
Looks good! I made a few comments in time_lapse_video.py, we can discuss them before merging. An overall comment is that some lines are too long, Noah recommends breaking them at 120 characters.

2021-04-29 20:55 UTC, JorgeGtz commented on plantcv/plantcv/visualize/time_lapse_video.py
> +import copy
not used

2021-04-29 20:55 UTC, JorgeGtz commented on plantcv/plantcv/visualize/time_lapse_video.py
> +from plantcv.plantcv import params
not used

2021-04-29 20:55 UTC, JorgeGtz commented on plantcv/plantcv/visualize/time_lapse_video.py
> +            warnings.warn(f"The sizes of images are not the same, an image resizing (cropping or zero-padding) will be done "
Is warnings.warn working as expected? Noah mentioned it only prints the warning in developing mode or something like that

2021-04-29 21:21 UTC, DannieSheng commented on plantcv/plantcv/visualize/time_lapse_video.py
> +    else:
I've fixed it

2021-04-29 21:26 UTC, DannieSheng commented on plantcv/plantcv/visualize/time_lapse_video.py
> +            list_img = list_img_
I don't have a good idea of how to do that. I just tried using set intersection to find the list of "extension free" file names that is provided by user and is in the provided directory. However with this "extension free" list of image names, we still need the extensions for every file. The assumption is that the file extensions are not necessarily the same (though normally it should not happen :)). Do you have good suggestions of this?

2021-04-29 21:46 UTC, nfahlgren commented on plantcv/plantcv/visualize/time_lapse_video.py
> +            list_img = list_img_
I haven't used this Python feature yet, but I think @JorgeGtz is suggesting you could make `temp_list_no_ext` and `list_img_no_ext` Python sets and use the `intersection` method to find the union of the two: https://www.w3schools.com/python/ref_set_intersection.asp

2021-04-29 21:52 UTC, DannieSheng commented on plantcv/plantcv/visualize/time_lapse_video.py
> +            list_img = list_img_
Yes, I've come to that step. The challenge is that after creating the `final_list_no_ext`, we will need the extension for every file. And the assumption is that not every file has the same file extension, i.e. the file extension is "file dependent". Although in most cases every image file should have the same extension. So there might be an extra step of finding the file extension for every file. But there might be solutions that I did not come up with.

2021-04-29 22:26 UTC, JorgeGtz commented on plantcv/plantcv/visualize/time_lapse_video.py
> +            list_img = list_img_
What about something like this:
```
temp_set = set(temp_list_no_ext)
for idx, f in enumerate(list_img_no_ext):
    if f in temp_set:
        list_img_.append(list_img[idx])
```

2021-04-29 22:35 UTC, DannieSheng commented on plantcv/plantcv/visualize/time_lapse_video.py
> +            list_img = list_img_
That's a good idea! Thank you!

2021-05-05 21:25 UTC, JorgeGtz approved these changes

2021-08-09 16:49 UTC, HaleySchuhl submitted a review, later dismissed

2021-11-23 18:04 UTC, nfahlgren requested changes

2021-11-23 18:04 UTC, nfahlgren commented on plantcv/plantcv/visualize/time_lapse_video.py
> +def time_lapse_video(img_directory, list_img=None, auto_sort = True, suffix_img=None, size_frame=None, fps=29.97,
```suggestion
def time_lapse_video(img_directory, list_img=None, auto_sort=True, suffix_img=None, size_frame=None, fps=29.97,
```

2022-02-28 20:07 UTC, nfahlgren commented
Some other changes to consider as I was using this yesterday:

* In debug mode all the frames are plotted, which can open too many plots for Jupyter - we need a different visualization (or none)
* The output filename is created from the input name and path, these can just be a single option for an output filename (which can include a path)

2022-03-24 21:11 UTC, HaleySchuhl approved these changes

2022-03-24 22:01 UTC, HaleySchuhl approved these changes

2022-03-24 22:10 UTC, merged