Gamma correct wrapper
danforthcenter/plantcv pull request #795
Opened 2021-06-29 22:16 UTC by jwheeler5

**Describe your changes**
Adds a plantcv function made by Haley (gamma_correct) that performs gamma correction on the input image. Wraps the skimage gamma correction function

**Type of update**

* New feature or feature enhancement
* Update to documentation

**Associated issues**

**Additional context**

2021-07-06 15:30 UTC, HaleySchuhl commented on plantcv/plantcv/transform/gamma_correct.py
> +# Gamma Correction Function Prototype
no longer a prototype! :)

2021-07-06 15:34 UTC, HaleySchuhl requested changes
Looks great! I added a minor comment about the header on the function, but the one thing missing is adding this function to the updating.md doc page. I updated the branch so it would be ready to merge once that last documentation page is amended.

2021-07-07 14:51 UTC, HaleySchuhl approved these changes
Awesome!

2021-07-23 15:33 UTC, nfahlgren approved these changes
Thanks @jwheeler5!

2021-07-23 16:04 UTC, merged