2D threshold
danforthcenter/plantcv pull request #840
Opened 2021-11-29 16:43 UTC by JorgeGtz

**Describe your changes**
This PR contains the function to perform color segmentation using a straight line in a 2D plane formed by two image channels.
This function is linked to the visualization function in PR #810. 

**Type of update**
Is this a:
* New feature or feature enhancement

**Associated issues**

**Additional context**

2022-01-25 15:37 UTC, HaleySchuhl submitted a review, later dismissed
Looks great so far. I think I recall some discussion about refactoring the name. Did we still want to try and reduce some of the redundancy?

2022-01-25 15:39 UTC, nfahlgren commented
Yeah, I think we discussed removing "threshold" from the function name since it's in the threshold submodule, but don't think we came to a firm decision about the function name

2022-01-26 20:03 UTC, HaleySchuhl approved these changes

2022-01-26 20:06 UTC, nfahlgren requested changes

2022-01-26 20:06 UTC, nfahlgren commented on docs/threshold_threshold_2_channels.md
> +**plantcv.threshold.threshold_2_channels**(*rgb_img, x_channel, y_channel, points, above=True, max_value=255*)
```suggestion
**plantcv.threshold.dual_channels**(*rgb_img, x_channel, y_channel, points, above=True, max_value=255*)
```

2022-01-26 20:06 UTC, nfahlgren commented on docs/updating.md
> +* post v4.0: bin_img **plantcv.threshold.threshold_2_channels**(*rgb_img, x_channel, y_channel, points, above=True, max_value=255*)
```suggestion
* post v4.0: bin_img **plantcv.threshold.dual_channels**(*rgb_img, x_channel, y_channel, points, above=True, max_value=255*)
```

2022-01-26 20:06 UTC, nfahlgren commented on docs/threshold_threshold_2_channels.md
> +## Threshold Two Channels
Rename file to `threshold_dual_channels.md`

2022-01-26 20:06 UTC, nfahlgren commented on mkdocs.yml
> +        - 'Threshold Two Channels': threshold_threshold_2_channels.md
Rename file to `threshold_dual_channels.md`

2022-01-26 21:27 UTC, nfahlgren approved these changes

2022-01-26 21:27 UTC, merged