Morphology segment combine update
danforthcenter/plantcv pull request #933
Opened 2022-08-12 20:53 UTC by HaleySchuhl

**Describe your changes**
Update the functionality to the `pcv.morphology.segment_combine`. This repairs the error with using `.remove` in issue #928 and simplifies the code so that it will only accept one list of segmentss to get combined. 

**Type of update**
Is this a:
* Bug fi

**Associated issues**
- closes #928 

**Additional context**
Add any other context about the problem here.

**For the reviewer**
See [this page](https://plantcv.readthedocs.io/en/stable/pr_review_process/) for instructions on how to review the pull request.
- [ ] PR functionality reviewed in a Jupyter Notebook
- [ ] All tests pass
- [ ] Test coverage remains 100%
- [ ] Documentation tested
- [ ] New documentation pages added to `plantcv/mkdocs.yml`
- [ ] Changes to function input/output signatures added to `updating.md`
- [ ] Code reviewed
- [ ] PR approved

2022-08-25 01:25 UTC, eyaler commented
Thanks! small comment:
```
if type(segment_list[0]) is not int:
```
does not gracefully handle the case of an empty segment_list

2022-08-30 18:56 UTC, HaleySchuhl commented
> Thanks! small comment:
> 
> ```
> if type(segment_list[0]) is not int:
> ```
> 
> does not gracefully handle the case of an empty segment_list

Very true! An added `fatal_error` with an informative message is a good idea.

2022-10-14 20:39 UTC, nfahlgren requested changes

2022-10-14 20:39 UTC, nfahlgren commented on docs/segment_combine.md
> +    - segment_list - List of segments to get combined to get combined
```suggestion
    - segment_list - List of segments to get combined
```

2022-11-08 18:01 UTC, nfahlgren approved these changes
Thanks!

2022-11-08 18:02 UTC, merged