Generalize photosynthesis filenaming
danforthcenter/plantcv pull request #984
Opened 2022-11-29 10:34 UTC by wurDevTim

**Describe your changes**
Phenovation changed the naming convention over time. Some small changes where made to add support for the new files. 
The new code is tested with data from both new and old cropreporters. 

**Type of update**
Is this an update of the cropreporter filenaming to make the OJIP analysis work with old and new cropreporters. 

**Associated issues**
https://github.com/danforthcenter/plantcv/issues/978

**Additional context**
The current git only contains files which uses the 'old' metadata format. 
I have some test images with the new format, who can send these to? Or where to upload? 
Maybe also add a test for these new files?

**For the reviewer**
See [this page](https://plantcv.readthedocs.io/en/stable/pr_review_process/) for instructions on how to review the pull request.
- [ ] PR functionality reviewed in a Jupyter Notebook
- [ ] All tests pass
- [ ] Test coverage remains 100%
- [ ] Documentation tested
- [ ] New documentation pages added to `plantcv/mkdocs.yml`
- [ ] Changes to function input/output signatures added to `updating.md`
- [ ] Code reviewed
- [ ] PR approved

2022-11-30 19:22 UTC, HaleySchuhl submitted a review, later dismissed
Hi @wurDevTim thanks for opening this PR. The code looks good, but the additional functionality at L78 - L80 and L121-L123 are not getting hit by the new test. Also a clarification sentence added to the documentation for `photosynthesis_read_cropreporter` would be good too!

2022-12-01 15:59 UTC, wurDevTim commented
@HaleySchuhl, I see, to hit those lines I have to add testdata from our cropreporter (the new file format).
The current ones are called `PSII_PSD_supopt_temp_btx623_22_rep1.DAT` and `PSII_PSD_supopt_temp_btx623_22_rep1.INF`.
Is there a naming preference for the new files? To make it easy to keep the two version apart or can I use any name I like?

2022-12-01 18:37 UTC, HaleySchuhl commented
@wurDevTim pretty much any name you'd like!

2022-12-02 15:24 UTC, wurDevTim commented
@HaleySchuhl  Added the files by making subfolders for the different cropreporter versions. Also updated the docs, let me know if  there are any other things you like me to change.

2023-02-18 14:58 UTC, wurDevTim commented
After quite some mails back and forth to phenovation we figured out that when 'SaveAllFrames' is set to '0' it only returns 3 frames: `Fdark, F0, Fm`  for the PSD and `Flight, Fp, Fmp` for the PSL. 

However,  the framelabels are not updated. therefore the code below tries to set frame labels to frames which don't exist:
```        
elif 'FqFmFrameFsp' in metadata:
   fsp_frame = int(metadata["FqFmFrameFsp"]) + 1
   fmp_frame = int(metadata["FqFmFrameFmp"]) + 1            
elif 'LtOjipFrameFsp' in metadata:
   fsp_frame = int(metadata["LtOjipFrameFsp"]) + 1
   fmp_frame = int(metadata["LtOjipFrameFmp"]) + 1
```

To make plantcv robust against this bug I changed the code to:
```
if metadata['SaveAllFrames'] == '0':
   fsp_frame = 1
   fmp_frame = 2
elif 'FqFmFrameFsp' in metadata:
   fsp_frame = int(metadata["FqFmFrameFsp"]) + 1
   fmp_frame = int(metadata["FqFmFrameFmp"]) + 1            
elif 'LtOjipFrameFsp' in metadata:
   fsp_frame = int(metadata["LtOjipFrameFsp"]) + 1
   fmp_frame = int(metadata["LtOjipFrameFmp"]) + 1
```

2023-06-13 19:32 UTC, nfahlgren requested changes
Hi @wurDevTim, sorry for the long delay. I think this looks great, I just have a few suggestions for simplifying the code a bit

2023-06-13 19:32 UTC, nfahlgren commented on plantcv/plantcv/photosynthesis/read_cropreporter.py
> +            fm_frame = int(metadata["DkOjipFrameFm"]) + 1
```suggestion
        # Default frames (when SaveAllFrames == 0)
        f0_frame = 1
        fm_frame = 2
        # If the method is labeled FvFm
        if 'FvFmFrameF0' in metadata:
            f0_frame = int(metadata["FvFmFrameF0"]) + 1
            fm_frame = int(metadata["FvFmFrameFm"]) + 1
        # If the method is labeled DkOjip
        if 'DkOjipFrameF0' in metadata:
            f0_frame = int(metadata["DkOjipFrameF0"]) + 1  # data cube includes Fdark at the beginning
            fm_frame = int(metadata["DkOjipFrameFm"]) + 1
```

2023-06-13 19:32 UTC, nfahlgren commented on plantcv/plantcv/photosynthesis/read_cropreporter.py
> +            fmp_frame = int(metadata["LtOjipFrameFmp"]) + 1
```suggestion
        # Default frames (when SaveAllFrames == 0)
        fsp_frame = 1
        fmp_frame = 2
        # If the method is labeled FqFm
        if 'FqFmFrameFsp' in metadata:
            fsp_frame = int(metadata["FqFmFrameFsp"]) + 1
            fmp_frame = int(metadata["FqFmFrameFmp"]) + 1
        # If the method is labeled LtOjip
        if 'LtOjipFrameFsp' in metadata:
            fsp_frame = int(metadata["LtOjipFrameFsp"]) + 1
            fmp_frame = int(metadata["LtOjipFrameFmp"]) + 1
```

2023-06-17 16:27 UTC, nfahlgren approved these changes

2023-06-17 16:28 UTC, merged